### Send PUT request with json body
DELETE http://localhost:8080/coffee/8828
Content-Type: application/json


### Send PUT request with json body
PUT http://localhost:8080/coffee/888
Content-Type: application/json

{
  "id": 888,
  "name": "blueberry juice"
}


### ### /coffee/999 PUT
PUT http://localhost:8080/coffee/999
Content-Type: application/json

{
  "id": 999,
  "name": "orange juice"
}

### /coffee/999 GET
GET http://localhost:8080/coffee/9992
Accept: application/json


### /coffee POST
POST http://localhost:8080/coffee
Content-Type: application/json

{
  "id": 999,
  "name": "vanilla latte"
}

### /coffee/{id} GET
GET http://localhost:8080/coffee/570ddea3-7d33-472f-80bc-80440e500f6c
Accept: application/json

### /coffee GET
GET http://localhost:8080/coffee
Accept: application/json




